CREATE DATABASE IF NOT EXISTS forums;

USE forums;

CREATE TABLE IF NOT EXISTS `forums` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
